### ISSUE TITLE
[vite-plugin-posthtml] Crashes on Node.js v16.8.0

### ISSUE THREAD

**Issue by vsnthdev** [chromeos/static-site-scaffold-modules#85]
Vite build fails due to `vite-plugin-posthtml` when executed on Node.js v16.8.0 with the following error 👇

```javascript
failed to load config from /Users/vasanth/Movies/hello-world/vite.config.js
error during build:
TypeError [ERR_INVALID_ARG_VALUE]: The property 'options.entryTypes' options.entryTypes can not set with options.type together. Received [ 'measure' ]
    at new NodeError (node:internal/errors:371:5)
    at PerformanceObserver.observe (node:internal/perf/observe:220:13)
    at posthtmlPlugin (/Users/vasanth/Movies/hello-world/node_modules/vite-plugin-posthtml/index.js:32:12)
    at default (file:///Users/vasanth/Movies/hello-world/vite.config.js?t=1630095273376:18:13)
    at loadConfigFromFile (/Users/vasanth/Movies/hello-world/node_modules/vite/dist/node/chunks/dep-972722fa.js:75866:15)
    at async resolveConfig (/Users/vasanth/Movies/hello-world/node_modules/vite/dist/node/chunks/dep-972722fa.js:75434:28)
    at async doBuild (/Users/vasanth/Movies/hello-world/node_modules/vite/dist/node/chunks/dep-972722fa.js:51931:20)
    at async build (/Users/vasanth/Movies/hello-world/node_modules/vite/dist/node/chunks/dep-972722fa.js:51919:16)
    at async CAC.<anonymous> (/Users/vasanth/Movies/hello-world/node_modules/vite/dist/node/cli.js:13998:9)
```

### 🛠 Steps to reproduce

1. Be on the latest Node.js version v16.8.0
2. Create a `package.json`
3. Install Vite & `vite-plugin-posthtml` as `devDependencies`
4. Set the property: `"type": "module"` in `package.json` to use ESM modules
5. Add the following content in `vite.config.js` 👇

```javascript
import { defineConfig } from 'vite'
import { posthtmlPlugin } from 'vite-plugin-posthtml'

export default () =>
    defineConfig({
        plugins: [
            // run PostHTML to construct the dist
            posthtmlPlugin({
                // PostHTML config
            }),
        ],
    })
```

6. Create `src/index.html` file
7. Run `npx vite --config vite.config.js build src`
8. There's the error 🙌

#### Version Information:
1. `node`: v16.8.0
2. `npm`: v7.21.0
3. `vite`: v2.5.1
4. `vite-plugin-posthtml`: v0.0.3

### 🔬 Additional Context

The latest known version of Node.js in which the plugin works perfectly is [v16.6.2](https://github.com/nodejs/node/releases/tag/v16.6.2) and `vite-plugin-posthtml` starts to crash right from the next release.

Thank you 😊

**Comment by zsdycs** [comment]
## This is a fatal bug !

I'm doing a build in github action and the problem occurs in both node version 16.6.2 and node version 14.18.2.

The strange thing is that when I buiid the same above node version on local windows there is no problem.

But for now, it is clear that this problem is generated by the following code👇:

https://github.com/chromeos/static-site-scaffold-modules/blob/fc4565852b6463998590b13ae45d03a93951e267/modules/vite-plugin-posthtml/index.js#L32

Can be obtained from document [PerformanceObserver.observe()](https://developer.mozilla.org/en-US/docs/Web/API/PerformanceObserver/observe).

![image](https://user-images.githubusercontent.com/44798353/148686855-13e60f1d-ffd0-4757-9c66-e47da061c444.png)

**Comment by zsdycs** [comment]
I fixed the error after making the following changes👇:

```diff
- observer.observe({ entryTypes: ['measure'], type: 'measure' }); 
+ observer.observe({ entryTypes: ['measure'] });
```

**Comment by pierremouchan** [comment]
This behavior still appears on my code, did you made pull request concerning this one? @zsdycs

**Comment by zsdycs** [comment]
> This behavior still appears on my code, did you made pull request concerning this one? @zsdycs 

👌

**Comment by zsdycs** [comment]
I'll submit a merger request later. But I think the merger will take some time. Because it seems that this library has not been active for a long time.

I suggest using [this](https://github.com/beaudar/beaudar/commit/753d05933d6464193466df3dab3e37db68a0199a) to solve your problem quickly. Replace this library with your own code.

**Comment by Snugug** [comment]
Hey all, sorry for the delay. I'm in the process of cleaning up this repo over the next week or so. I'll push a fix then.

**Comment by samjeffress** [comment]
@Snugug any word on the cleanup or if we should switch to a different option?

**Comment by zsdycs** [comment]
> I'll submit a merger request later. But I think the merger will take some time. Because it seems that this library has not been active for a long time.我稍后会提交合并请求。但我认为合并需要一些时间。因为这个库似乎很久没有活跃了。
> 
> I suggest using [this](https://github.com/beaudar/beaudar/commit/753d05933d6464193466df3dab3e37db68a0199a) to solve your problem quickly. Replace this library with your own code.我建议使用它来快速解决您的问题。将此库替换为您自己的代码。

Sorry, I forgot to submit the PR. You can follow the merger status of [this PR](https://github.com/chromeos/static-site-scaffold-modules/pull/130) for this issue.
